name: projeto_pedido_vendas
description: "Projeto Academico para Emissão de Pedidos."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  path: ^1.8.3
  sqflite: ^2.3.2
  multi_dropdown: ^1.0.9
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0 # A versão mais recente compatível com o intl 0.18.1
  font_awesome_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
